source 'https://github.com/CocoaPods/Specs.git'

target 'CYKit' do
    
platform:ios,'8.0'
pod 'Masonry',             '~> 1.0.2'
pod 'BlocksKit',           '~> 2.2.5'
pod 'CocoaLumberjack',     '~> 3.0.0'
pod 'FMDB',		   '~> 2.7'
end

